defmodule LetterGrade do
  def rank(score) when 5 < score, do: "S+#{score-5}"
  def rank(score) when 5 == score, do: "A"
  def rank(score) when 4 == score, do: "B"
  def rank(score) when 3 == score, do: "C"
  def rank(score) when 2 == score, do: "D"
  def rank(score) when 1 == score, do: "F"
  def rank(_score), do: "0"

  def percent(score) when 399 < score, do: "S+"
  def percent(score) when 199 < score, do: "S"
  def percent(score) when  99 < score, do: "S-"
  def percent(score) when  96 < score, do: "A+"
  def percent(score) when  92 < score, do: "A"
  def percent(score) when  89 < score, do: "A-"
  def percent(score) when  86 < score, do: "B+"
  def percent(score) when  82 < score, do: "B"
  def percent(score) when  79 < score, do: "B-"
  def percent(score) when  76 < score, do: "C+"
  def percent(score) when  72 < score, do: "C"
  def percent(score) when  69 < score, do: "C-"
  def percent(score) when  66 < score, do: "D+"
  def percent(score) when  62 < score, do: "D"
  def percent(score) when  59 < score, do: "D-"
  def percent(score) when  49 < score, do: "F+"
  def percent(score) when   9 < score, do: "F"
  def percent(score) when   0 < score, do: "F-"
  def percent(_score), do: "0"
end

